#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HermesLogin.Resource", IsApplication=true)]

namespace HermesLogin
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonSignInStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonSignUpMailStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int EditTextStyle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ProgressBarStyle = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000c
			public const int btnDialogSignUp = 2131230732;
			
			// aapt resource value: 0x7f080000
			public const int btnReservarCancha = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int btnSignIn = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int btnSignUpEmail = 2131230724;
			
			// aapt resource value: 0x7f08000f
			public const int item_subtitle = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int item_title = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int menu = 2131230737;
			
			// aapt resource value: 0x7f080005
			public const int progressBar1 = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int sample_content_fragment = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int sample_main_layout = 2131230726;
			
			// aapt resource value: 0x7f08000d
			public const int sliding_tabs = 2131230733;
			
			// aapt resource value: 0x7f080003
			public const int textOr = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int txtCreateAcount = 2131230721;
			
			// aapt resource value: 0x7f080009
			public const int txtEmail = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int txtName = 2131230728;
			
			// aapt resource value: 0x7f08000a
			public const int txtPassword = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int txtRepeatPassword = 2131230731;
			
			// aapt resource value: 0x7f08000e
			public const int viewpager = 2131230734;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int HermesActivity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ReservarCanchaActivity = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SignUpDialog = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int slidingTabFragment = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int slidingTabPage = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int actionbar_menu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int txtContraseña = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int txtCorreo = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int txtCrearCuenta = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int txtCrearCuentaMail = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int txtIniciarSesion = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int txtNombre = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int txtOr = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int txtRepetirContraseña = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int txtReservarCancha = 2131034122;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int dialog_animation = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
