#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HermesLogin.Resource", IsApplication=true)]

namespace HermesLogin
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonSignInStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonSignUpMailStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int EditTextStyle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ProgressBarStyle = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070009
			public const int btnDialogSignUp = 2131165193;
			
			// aapt resource value: 0x7f070001
			public const int btnSignIn = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int btnSignUpEmail = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int progressBar1 = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int textOr = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int txtCreateAcount = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int txtEmail = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int txtName = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int txtPassword = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int txtRepeatPassword = 2131165192;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int SignUpDialog = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int txtContraseña = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int txtCorreo = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int txtCrearCuenta = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int txtCrearCuentaMail = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int txtIniciarSesion = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int txtNombre = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int txtOr = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int txtRepetirContraseña = 2131034120;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int dialog_animation = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
